import { StopCircle, Trash2 } from 'lucide-react';
import { useI18n } from '@/shared/i18n';

export interface ActiveProcess { process: { kill(): void; input: WritableStream<string> }; output: string; isRunning: boolean; command: string; }
interface ServicePanelProps {
  ports: Array<{ port: number; url: string }>;
  processes: ReadonlyMap<string, ActiveProcess>;
  onClearPort: (port: number) => void;
  onKillProcess: (processId: string) => void;
}

export function ServicesPanel({ ports, processes, onClearPort, onKillProcess }: ServicePanelProps) {
  const { t, format } = useI18n();
  const runningProcesses = Array.from(processes.entries()).filter(([, process]) => process.isRunning);
  return <div className="motion-panel-in" style={{ flex: 1, overflowY: 'auto', padding: '16px', backgroundColor: 'var(--color-bg)', borderRadius: 'var(--radius-large)', display: 'flex', flexDirection: 'column', gap: '24px', height: '100%' }}>
    <section className="services-section"><h3 style={{ fontSize: '14px', fontWeight: 600, color: 'var(--color-text)', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'var(--color-success)' }} />{t('services.ports')}</h3>{ports.length === 0 ? <div style={{ fontSize: '13px', color: 'var(--color-text-secondary)', padding: '16px', textAlign: 'center' }}>{t('services.noPorts')}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>{ports.map((port) => <div key={port.port} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px', border: '1px solid var(--color-border)', borderRadius: '6px', backgroundColor: 'var(--color-surface)', gap: '12px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '12px', minWidth: 0, flex: 1 }}><span style={{ fontSize: '14px', fontWeight: 500, color: 'var(--color-text)', whiteSpace: 'nowrap' }}>{format('services.port', { port: port.port })}</span><a href={port.url} target="_blank" rel="opener" style={{ fontSize: '13px', color: 'var(--color-primary)', textDecoration: 'none', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }} title={port.url}>{port.url} ↗</a></div><button onClick={() => onClearPort(port.port)} style={{ background: 'none', border: 'none', color: '#ff4d4f', cursor: 'pointer', padding: '6px', borderRadius: '4px', flexShrink: 0, display: 'flex' }} title={t('services.clear')}><Trash2 size={16} /></button></div>)}</div>}</section>
    <section className="services-section"><h3 style={{ fontSize: '14px', fontWeight: 600, color: 'var(--color-text)', marginBottom: '12px', display: 'flex', alignItems: 'center', gap: '8px' }}><span style={{ width: '8px', height: '8px', borderRadius: '50%', backgroundColor: 'var(--color-primary)' }} />{t('services.processes')}</h3>{runningProcesses.length === 0 ? <div style={{ fontSize: '13px', color: 'var(--color-text-secondary)', padding: '16px', textAlign: 'center' }}>{t('services.noProcesses')}</div> : <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>{runningProcesses.map(([id, process]) => <div key={id} style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '12px', border: '1px solid var(--color-border)', borderRadius: '6px', backgroundColor: 'var(--color-surface)', gap: '12px' }}><div style={{ display: 'flex', flexDirection: 'column', gap: '4px', overflow: 'hidden', minWidth: 0, flex: 1 }}><div style={{ fontSize: '12px', color: 'var(--color-text-secondary)', fontFamily: 'monospace' }}>{id}</div><div style={{ fontSize: '14px', color: 'var(--color-text)', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' }} title={`$ ${process.command}`}>$ {process.command}</div></div><button onClick={() => onKillProcess(id)} style={{ flexShrink: 0, background: 'none', border: 'none', color: '#ff4d4f', cursor: 'pointer', padding: '6px', borderRadius: '4px', display: 'flex' }} title={t('services.kill')}><StopCircle size={18} /></button></div>)}</div>}</section>
  </div>;
}
